### ISSUE TITLE
Login after installation

### ISSUE THREAD

**Issue by uw0wu** [sunuilhamp/Easy-WMS#2]
Hello. I need help.
I installed the system: Ubuntu 20.04.5 + Apache2 + MariaDB + PHP 7.4  
Database migrated from sqlite to MariaDB.
The login homepage is displayed normally.
Login with data: admin@easywms.com : admin
The system redirects me to the address: <domen>/login
But the next page doesn't exist.
Here is the console data: POST http://192.168.100.12/login 404 (Not Found)

Help me please. What is the problem?

**Comment by sunuilhamp** [comment]
Hi, you should check the developer tools on your browser carefully to find the problem because I've just tested the app on my System: Windows 11 + Laragon.
It worked well.

**Comment by uw0wu** [comment]
Thanks for your reply.
The problem is not with the browser.
I get Not Found - in all browsers.
Tried using another computer - same result.

Maybe I didn't make some settings?

**Comment by sunuilhamp** [comment]
maybe you should check your `$config[base_url]` and check the url correctly

after you logged in you should get `[base_url]/home` if you got it wrong, then you should custom the controller to make sure nothing changed from my github code.

**Comment by uw0wu** [comment]
The problem was solved.
Added by:
sudo a2enmod rewrite
sudo apt install libapache2-mod-php

Thank you for your participation.
